"""Streaming, transaction-consistent SQLite restoration drills.

Use only with a trusted database owned by this installation. This is an operator
utility, never an import endpoint. JSON preserves embedded NULs that SQLite's
SQL quote()/iterdump() truncates. FTS shadow pages are regenerated by the same
SQLite version, while their virtual table contents and rowids are retained.
"""
from __future__ import annotations
import argparse
import base64
import gzip
import hashlib
import json
from pathlib import Path
import sqlite3
import sys


def identifier(value): return '"' + value.replace('"', '""') + '"'
def encode(value): return {'blob':base64.b64encode(value).decode()} if isinstance(value, bytes) else value
def decode(value): return base64.b64decode(value['blob'],validate=True) if isinstance(value,dict) else value


def snapshot(path, output):
    db=sqlite3.connect(Path(path).resolve().as_uri()+'?mode=ro',uri=True)
    checksum=hashlib.sha256();counts={}
    try:
        db.execute('BEGIN')
        objects=db.execute('SELECT type,name,sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY rowid').fetchall()
        info={r[1]:r for r in db.execute('PRAGMA table_list') if r[0]=='main'}
        tables=[]
        for kind,name,sql in objects:
            if kind!='table' or info[name][2]=='shadow': continue
            columns=[r[1] for r in db.execute('PRAGMA table_xinfo('+identifier(name)+')') if r[6]==0]
            if not info[name][4]: columns=['rowid']+columns
            tables.append({'name':name,'sql':sql,'columns':columns})
        schema={'version':1,'sqlite':sqlite3.sqlite_version,'tables':tables,
            'after':[sql for kind,name,sql in objects if kind in ('index','trigger','view')]}
        with gzip.GzipFile(fileobj=output,mode='wb',compresslevel=1) as stream:
            def write(value):
                raw=(json.dumps(value,separators=(',',':'))+'\n').encode()
                checksum.update(raw);stream.write(raw)
            write({'schema':schema})
            for table in tables:
                name=table['name'];counts[name]=0
                columns=','.join(identifier(c) for c in table['columns'])
                for row in db.execute('SELECT '+columns+' FROM '+identifier(name)):
                    write({'table':name,'row':[encode(v) for v in row]});counts[name]+=1
            stream.write((json.dumps({'complete':checksum.hexdigest(),'counts':counts})+'\n').encode())
        return {'counts':counts,'sha256':checksum.hexdigest(),'sqlite':sqlite3.sqlite_version}
    finally:db.close()


def restore(source, destination):
    destination=Path(destination)
    with destination.open('xb') as created:
        import os
        os.chmod(destination,0o600)
    db=sqlite3.connect(destination);checksum=hashlib.sha256();counts={};complete=False
    try:
        with gzip.GzipFile(fileobj=source,mode='rb') as stream:
            header=stream.readline();schema=json.loads(header)['schema'];checksum.update(header)
            if schema['version']!=1:raise ValueError('Unsupported backup format')
            if schema['sqlite']!=sqlite3.sqlite_version:
                raise ValueError('Restore with the source SQLite version to preserve FTS tokenization')
            db.execute('BEGIN');statements={}
            for table in schema['tables']:
                name=table['name'];counts[name]=0
                if name!='sqlite_sequence':db.execute(table['sql'])
                else:db.execute('DELETE FROM sqlite_sequence')
                columns=','.join(identifier(c) for c in table['columns'])
                statements[name]='INSERT INTO '+identifier(name)+'('+columns+') VALUES('+','.join('?' for _ in table['columns'])+')'
            for raw in stream:
                value=json.loads(raw)
                if 'complete' in value:
                    if complete or value['complete']!=checksum.hexdigest() or value['counts']!=counts:
                        raise ValueError('Backup checksum or row counts mismatch')
                    complete=True
                    if stream.read(1):raise ValueError('Unexpected data after backup footer')
                    break
                checksum.update(raw);name=value['table']
                if name=='sqlite_sequence' and counts[name]==0:db.execute('DELETE FROM sqlite_sequence')
                db.execute(statements[name],[decode(v) for v in value['row']]);counts[name]+=1
            if not complete:raise ValueError('Incomplete backup')
            if counts.get('sqlite_sequence')==0:db.execute('DELETE FROM sqlite_sequence')
            for sql in schema['after']:db.execute(sql)
            db.commit()
        integrity=[r[0] for r in db.execute('PRAGMA integrity_check')]
        if integrity!=['ok']:raise ValueError('Restored database integrity verification failed')
        return {'integrity':'ok','counts':counts,'sha256':checksum.hexdigest(),'sqlite':sqlite3.sqlite_version}
    finally:db.close()


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    sub=parser.add_subparsers(dest='mode',required=True)
    sub.add_parser('export').add_argument('database',type=Path)
    sub.add_parser('restore').add_argument('database',type=Path)
    args=parser.parse_args()
    result=snapshot(args.database,sys.stdout.buffer) if args.mode=='export' else restore(sys.stdin.buffer,args.database)
    print(json.dumps(result),file=sys.stderr)


if __name__=='__main__':main()
