import { render, screen, fireEvent, waitFor, cleanup, act } from '@testing-library/react'
import { it, expect, vi, afterEach } from 'vitest'
import { StudioComputerWindow } from './computer-window'
const seen=vi.hoisted(()=>({connections:[] as any[]}))
vi.mock('@novnc/novnc',()=>({default:class {
 events:Record<string,()=>void>={}
 viewOnly=false;disconnect=vi.fn();scaleViewport=false;resizeSession=false
 constructor(public target:HTMLElement,public url:string,public options:unknown){seen.connections.push(this)}
 addEventListener(name:string,callback:()=>void){this.events[name]=callback;if(name==='connect')callback()}
 sendCredentials(){}
}}))
afterEach(()=>{cleanup();seen.connections=[];vi.useRealTimers()})
vi.mock('./workspace-controls',()=>({ComputerWindows:()=>null}))
vi.mock('./open-computer',()=>({OpenComputerButton:()=>null}))
it('uses the real desktop session in view-only mode and disconnects only the viewer',async()=>{
 const getSession=vi.fn().mockResolvedValue({ok:true,computerName:'Existing team',websocketUrl:'wss://unit.invalid/viewer',password:'unit-only'})
 Object.defineProperty(window,'hermesDesktop',{configurable:true,value:{orgoDesktop:{getSession}}})
 const view=render(<StudioComputerWindow />)
 await screen.findByRole('heading',{name:'Existing team',level:1})
 await waitFor(()=>expect(seen.connections.length).toBe(1))
 const connection=seen.connections[0]
 expect(connection.url).toBe('wss://unit.invalid/viewer');expect(connection.options).toEqual({credentials:{password:'unit-only'},shared:true})
 expect(connection.viewOnly).toBe(true)
 fireEvent.click(screen.getByRole('button',{name:'Control desktop'}));expect(connection.viewOnly).toBe(false)
 expect(screen.getByRole('status').textContent).toContain('Existing agents keep running')
 view.unmount();expect(connection.disconnect).toHaveBeenCalledOnce()
 expect(getSession).toHaveBeenCalledWith('default')
})

it('reconnects a dropped desktop to the same computer with fresh credentials and no manual control', async () => {
 const getSession=vi.fn().mockResolvedValue({ok:true,computerName:'Existing team',websocketUrl:'wss://unit.invalid/viewer',password:'refreshed'})
 Object.defineProperty(window,'hermesDesktop',{configurable:true,value:{orgoDesktop:{getSession}}})
 render(<StudioComputerWindow />)
 await screen.findByRole('heading',{name:'Existing team',level:1})
 await waitFor(()=>expect(seen.connections).toHaveLength(1))
 fireEvent.click(screen.getByRole('button',{name:'Control desktop'}))
 vi.useFakeTimers()
 act(()=>seen.connections[0].events.disconnect())
 expect(screen.getByRole('status').textContent).toContain('View only')
 await act(async()=>vi.advanceTimersByTimeAsync(1000))
 expect(getSession).toHaveBeenCalledTimes(2)
 expect(getSession.mock.calls).toEqual([['default'],['default']])
 expect(seen.connections[1].viewOnly).toBe(true)
 expect(seen.connections[0].disconnect).toHaveBeenCalled()
})
it('bounds retries when the remote computer stays unavailable and cancels retries on close', async () => {
 vi.useFakeTimers()
 const getSession=vi.fn().mockResolvedValue({ok:false,error:{message:'Offline'}})
 Object.defineProperty(window,'hermesDesktop',{configurable:true,value:{orgoDesktop:{getSession}}})
 const view=render(<StudioComputerWindow />)
 await act(async()=>{})
 for(const delay of [1000,2000,4000]) await act(async()=>vi.advanceTimersByTimeAsync(delay))
 expect(getSession).toHaveBeenCalledTimes(4)
 expect(screen.getByRole('alert').textContent).toContain('Use Reconnect')
 await act(async()=>vi.advanceTimersByTimeAsync(60000))
 expect(getSession).toHaveBeenCalledTimes(4)
 fireEvent.click(screen.getByRole('button',{name:'Reconnect'}))
 await act(async()=>{})
 expect(getSession).toHaveBeenCalledTimes(5)
 view.unmount()
 await act(async()=>vi.advanceTimersByTimeAsync(60000))
 expect(getSession).toHaveBeenCalledTimes(5)
})
it('disconnects the viewer and shows connection failure when the VNC handshake stalls', async () => {
 vi.useFakeTimers()
 const getSession=vi.fn().mockImplementation(()=>new Promise(()=>{}))
 Object.defineProperty(window,'hermesDesktop',{configurable:true,value:{orgoDesktop:{getSession}}})
 const view=render(<StudioComputerWindow />)
 await act(async()=>vi.advanceTimersByTimeAsync(30000))
 expect(screen.getByRole('status').textContent).toContain('Reconnecting')
 view.unmount()
 await act(async()=>vi.advanceTimersByTimeAsync(60000))
 expect(getSession).toHaveBeenCalledTimes(1)
})

it('starts with a contained screen and expands/returns without replacing the desktop connection', async () => {
 const getSession=vi.fn().mockResolvedValue({ok:true,computerName:'Existing team',websocketUrl:'wss://unit.invalid/viewer',password:'unit-only'})
 Object.defineProperty(window,'hermesDesktop',{configurable:true,value:{orgoDesktop:{getSession}}})
 render(<StudioComputerWindow />)
 await waitFor(()=>expect(seen.connections).toHaveLength(1))
 const connection=seen.connections[0]
 const panel=screen.getByRole('region',{name:'Live Orgo desktop'})
 expect(panel.style.aspectRatio).toBe('16 / 10')
 expect(panel.style.maxHeight).toBe('240px')
 expect(screen.getByRole('complementary',{name:'Workspace navigation'})).toBeTruthy()
 const rightPanel=screen.getByRole('complementary',{name:'Computer panel'})
 expect(rightPanel.style.maxWidth).toBe('360px')
 expect(screen.getByRole('region',{name:'Workspace'}).nextElementSibling).toBe(rightPanel)
 fireEvent.click(screen.getByRole('button',{name:'Expand screen'}))
 expect(panel.style.height).toBe('65vh')
 expect(panel.style.maxHeight).toBe('')
 expect(screen.getByRole('button',{name:'Return to workspace'})).toBeTruthy()
 fireEvent.keyDown(window,{key:'Escape'})
 expect(screen.getByRole('button',{name:'Expand screen'})).toBeTruthy()
 expect(panel.style.aspectRatio).toBe('16 / 10')
 expect(panel.style.maxHeight).toBe('240px')
 expect(seen.connections).toHaveLength(1)
 expect(connection.disconnect).not.toHaveBeenCalled()
 expect(getSession).toHaveBeenCalledTimes(1)
})
